# Generated by Django 2.2.8 on 2020-04-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='createTime',
            field=models.DateTimeField(auto_now=True, verbose_name='回复时间'),
        ),
        migrations.AddField(
            model_name='collections',
            name='createTime',
            field=models.DateTimeField(auto_now=True, verbose_name='收藏时间时间'),
        ),
        migrations.AddField(
            model_name='question',
            name='createTime',
            field=models.DateTimeField(auto_now=True, verbose_name='提问时间'),
        ),
        migrations.AlterField(
            model_name='users',
            name='img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='img', verbose_name='用户头像'),
        ),
    ]
