# Generated by Django 2.2.8 on 2020-04-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200423_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(default='新用户', max_length=10, verbose_name='昵称'),
        ),
    ]
