# Generated by Django 2.2.8 on 2020-04-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200423_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('T', '已解决'), ('F', '为解决')], default='F', max_length=1, verbose_name='是否解决'),
        ),
    ]
