# Generated by Django 2.2.8 on 2020-04-24 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_question_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='createTime',
            field=models.DateTimeField(auto_now=True, verbose_name='收藏时间'),
        ),
        migrations.CreateModel(
            name='LikesRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='点在时间')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Answer', verbose_name='问题')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '点赞管理',
                'verbose_name_plural': '点赞管理',
            },
        ),
    ]
