# Generated by Django 2.2.8 on 2020-04-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200424_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comments',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
    ]
