# Generated by Django 2.0.3 on 2020-04-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_question_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bonus',
            field=models.IntegerField(default=0, verbose_name='赏金'),
        ),
    ]
