# Generated by Django 2.0.3 on 2020-04-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200425_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='bonus',
            field=models.IntegerField(default=10, verbose_name='悬赏金额'),
        ),
    ]
