# Generated by Django 2.0.3 on 2020-06-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200425_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': '回复管理', 'verbose_name_plural': '回复管理'},
        ),
        migrations.AddField(
            model_name='users',
            name='college',
            field=models.CharField(default='', max_length=10, verbose_name='院系'),
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('T', '男'), ('T', '女')], default='T', max_length=1, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='users',
            name='major',
            field=models.CharField(default='', max_length=20, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('T', '已解决'), ('F', '未解决')], default='F', max_length=1, verbose_name='是否解决'),
        ),
        migrations.AlterField(
            model_name='users',
            name='createTime',
            field=models.DateTimeField(auto_now=True, verbose_name='注册时间'),
        ),
    ]
